# 예전(17f1f07 이전) 순번 id — 외움 기록 옮기기 전용. 지금 상태로 고정한 표라 카드를 더해도 고치지 않는다.
# 이 표에 없는 카드(새로 더한 카드)는 옮겨 올 옛 기록이 없다.
LEGACY_IDS = {
    '불러오기 · 크기 · 앞부분': 't1base-1',
    '컬럼 선택 · loc / iloc': 't1base-2',
    '조건 필터링 · 다중 조건': 't1base-3',
    '정렬 후 N번째 값': 't1base-4',
    'value_counts — 이름인가 개수인가': 't1base-5',
    '기초 통계 함수': 't1base-6',
    '결측치 확인 · 제거': 't1prep-1',
    '결측치 대체 — 값은 먼저 구한다': 't1prep-2',
    '그룹별 값으로 결측치 채우기': 't1prep-3',
    'IQR 이상치': 't1prep-4',
    '이상치 바꾸기 · 표준화': 't1prep-5',
    '중복 처리': 't1prep-6',
    '파생변수 · 구간 나누기': 't1derive-1',
    '값 바꾸기 · map · apply': 't1derive-2',
    '문자열 처리': 't1derive-3',
    '날짜 처리': 't1derive-4',
    '날짜 차이 · 기간': 't1derive-5',
    'groupby 기본': 't1agg-1',
    'agg 이름 붙여 여러 집계': 't1agg-2',
    '집계 결과에서 하나 고르기': 't1agg-3',
    'pivot_table · crosstab · unstack': 't1agg-4',
    '병합 · 이어 붙이기': 't1agg-5',
    '상관계수 · 순위 · 누적': 't1agg-6',
    '정수 처리 — int 는 버림이다': 't1answer-1',
    '음수 · 올림 · 내림': 't1answer-2',
    '처음부터 정수인 값': 't1answer-3',
    '최종 답은 값 하나만': 't1answer-4',
    '라이브러리 · 데이터 불러오기': 't2prep-1',
    'target 찾기 · 분류인가 회귀인가': 't2prep-2',
    'X · y 분리 — id 는 뺀다': 't2prep-3',
    '결측 채우기 — 기준은 train': 't2prep-4',
    '원-핫 인코딩 + 컬럼 맞추기': 't2prep-5',
    '라벨 인코딩 (대안)': 't2prep-6',
    '전처리 함수로 묶기 (교재 패턴)': 't2prep-7',
    '스케일링 (필요할 때만)': 't2prep-8',
    '검증 데이터 나누기': 't2model-1',
    '분류 모델': 't2model-2',
    '양성 확률 꺼내기': 't2model-3',
    '분류 평가지표': 't2model-4',
    '회귀 모델': 't2model-5',
    '회귀 평가지표': 't2model-6',
    '다른 모델로 바꿔 보기': 't2model-7',
    '최종 학습 — 전체 train 으로': 't2model-8',
    'result.csv 만들기': 't2submit-1',
    '저장한 파일 다시 읽어 확인': 't2submit-2',
    '제출값 형태 점검': 't2submit-3',
    '라이브러리': 't3test-1',
    '단일표본 t-검정': 't3test-2',
    '검정 방향 alternative': 't3test-3',
    '정규성 · 등분산 검정': 't3test-4',
    '독립표본 t-검정': 't3test-5',
    '대응표본 t-검정': 't3test-6',
    '신뢰구간': 't3test-7',
    '검정통계량 직접 계산': 't3test-8',
    '비율 검정 (1표본 · 2표본)': 't3test-9',
    '일원분산분석 (scipy)': 't3anova-1',
    '분산분석표 (statsmodels)': 't3anova-2',
    '사후검정 (Tukey)': 't3anova-3',
    '카이제곱 적합도': 't3anova-4',
    '카이제곱 독립성': 't3anova-5',
    '가설 기각 판단': 't3anova-6',
    '상관분석': 't3reg-1',
    '선형회귀 OLS': 't3reg-2',
    '회귀 결과에서 값 꺼내기': 't3reg-3',
    'formula 로 회귀 (범주형 포함)': 't3reg-4',
    '신뢰구간 · 예측': 't3reg-5',
    '유의한 변수만 다시 적합': 't3reg-6',
    '더미 변수 만들기': 't3reg-7',
    '로지스틱 회귀 (statsmodels)': 't3logit-1',
    '오즈비': 't3logit-2',
    '예측 확률 · 오분류율': 't3logit-3',
    'sklearn 으로 같은 값 내기': 't3logit-4',
    '함수 이름 · 인자 찾기': 'env-1',
    '출력이 잘릴 때': 'env-2',
    '버전 확인': 'env-3',
}
